name: test-selenium

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'

    - name: Install dependencies
      run: npm ci

    - name: Build and run development server
      run: npm run dev&

    - name: Run tests
      run: npm run test-browserstack
